# Generated by Django 4.2 on 2023-05-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_documentofp_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentofp',
            name='foto',
        ),
    ]
