# Generated by Django 4.2 on 2023-05-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_documentofp_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofp',
            name='foto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
