# Generated by Django 4.2 on 2023-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_documentolg'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentolg',
            name='foto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
