# Generated by Django 4.2 on 2023-05-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_documentolg_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolg',
            name='assinatura',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='assunto',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='ementa',
            field=models.TextField(default=None),
        ),
    ]
