# Generated by Django 4.2 on 2023-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_documentolg_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofp',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='documentolg',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação')], default='', max_length=50),
        ),
    ]
