# Generated by Django 4.2 on 2023-05-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_documentofp_categoria_documentolg_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofp',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação')], default='Ficha Primária', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação')], default='Legislação', max_length=50),
        ),
    ]
