# Generated by Django 4.2 on 2023-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_documentofp_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolg',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação')], default='LEGISLACAO', max_length=50),
        ),
    ]
