# Generated by Django 4.2 on 2023-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_documentolg_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofp',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação')], default='FICHA PRIMARIA', max_length=50),
        ),
    ]
