# Generated by Django 4.2 on 2023-09-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_documentofp_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofp',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
