# Generated by Django 4.2 on 2023-09-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_remove_documentofp_foto_remove_documentolg_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofp',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documentofp',
            name='palavras_chave',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentofp',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentofp',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documentofp',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação')], default='LEGISLACAO', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='data',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='entidade_origem',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='local',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='palavras_chave',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='responsavel',
            field=models.CharField(max_length=100),
        ),
    ]
