# Generated by Django 4.2 on 2023-09-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_alter_documentofp_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofp',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação'), ('LIVRO', 'Livro')], default='FICHA PRIMARIA', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentolg',
            name='categoria',
            field=models.CharField(choices=[('FICHA PRIMARIA', 'Ficha Primária'), ('LEGISLACAO', 'Legislação'), ('LIVRO', 'Livro')], default='LEGISLACAO', max_length=100),
        ),
    ]
