# Generated by Django 4.2 on 2023-09-15 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0016_alter_documentofp_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofp',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuariofp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentolg',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuariolg', to=settings.AUTH_USER_MODEL),
        ),
    ]
